"""empty message

Revision ID: ded95dfb65b0
Revises: None
Create Date: 2016-09-08 02:26:29.619866

"""

# revision identifiers, used by Alembic.
revision = 'ded95dfb65b0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revel_resource', sa.Column('revel_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revel_resource', 'revel_url')
    ### end Alembic commands ###
